### ISSUE TITLE
Change deprecated dependency

### ISSUE THREAD

**Issue by jearangoo** [alenon/grpc-mock-server#139]
When installing with nodejs version 17 i got an error with node-gyp and this warning 
```
 grpc@1.24.11: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.
```
Can you replace grpc deprecated dependecy for @grpc/grpc-js?

**Comment by alenon** [comment]
@jearangoo If you wish to contribute, you can create a PR and I'll approve and merge it. Alternativly I'll, but it will take some time for me.

**Comment by jearangoo** [comment]
thank you @alenon, i will take a look at it

**Comment by alenon** [comment]
Fixed! Closing ...
