### ISSUE TITLE
GRPC server bind function not implemented

### ISSUE THREAD

**Issue by ckfngod** [alenon/grpc-mock-server#168]
Getting `Not implemented. Use bindAsync() instead` error when constructing `GrpcMockServer` using `grpc-mock-server@1.3.0` and `grpc-js@1.5.3`. Looks like the GRPC server `bind` function was disabled at some point in favour of `bindAsync`.

**Comment by alenon** [comment]
@ckfngod thank you for raising the flag! The issue is resolved! 
The version 1.3.0 was removed.

**Please use the new version of the package 2.0.0**

P.S. added test, so such an issue shouldn't happen in the future.
